---
title: "Remise en route du seal AA3"
author: "Engels Guyliann"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_height: 5.5
    fig_width: 7.4
    number_sections: yes
    toc: yes
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE, results='hide'}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
source("../../R/import_aa3_txt.R")
SciViews::R
```


```{r import}
inorga <- aa3_txt(file_aa3_txt = "../../data/raw/190212C.TXT", project = "test", topic = NULL)
```

# Méthode inorganique

## PO4

```{r}
chart(inorga, PO4_conc ~ date_time %group=% 1 %col=%sample_type) +
  geom_line() +
  geom_point()
```



```{r}
inorga %>.%
  filter(., sample_type %in% c("CALB", "SAMP") & sample_id != "mesoA" & sample_id != "mesoB") %>.%
  mutate(., sample_id = factor(sample_id, levels = c("cal1", "cal5", "cal10", "cal15", 
                                                     "cal20", "cal25", "cal30"))) %>.%
  group_by(., sample_id) %>.%
  summarise(., mean = mean(PO4_conc), sd = sd(PO4_conc), cv = sd(PO4_conc)/mean(PO4_conc), n = n()) %>.%
  rmarkdown::paged_table(.)
```


## NO3

```{r}
chart(inorga, NOx_conc ~ date_time %group=% 1 %col=%sample_type) +
  geom_line() +
  geom_point()
```

```{r}
inorga %>.%
  filter(., sample_type %in% c("CALB", "SAMP") & sample_id != "mesoA" & sample_id != "mesoB") %>.%
  mutate(., sample_id = factor(sample_id, levels = c("cal1", "cal5", "cal10", "cal15", 
                                                     "cal20", "cal25", "cal30"))) %>.%
  group_by(., sample_id) %>.%
  summarise(., mean = mean(NOx_conc), sd = sd(NOx_conc), cv = sd(NOx_conc)/mean(NOx_conc), n = n()) %>.%
  rmarkdown::paged_table(.)
```

## NH4

```{r}
chart(inorga, NH4_conc ~ date_time %group=% 1 %col=%sample_type) +
  geom_line() +
  geom_point()
```


```{r}
inorga %>.%
  filter(., sample_type %in% c("CALB", "SAMP") & sample_id != "mesoA" & sample_id != "mesoB") %>.%
  mutate(., sample_id = factor(sample_id, levels = c("cal1", "cal5", "cal10", "cal15", 
                                                     "cal20", "cal25", "cal30"))) %>.%
  group_by(., sample_id) %>.%
  summarise(., mean = mean(NH4_conc), sd = sd(NH4_conc), cv = sd(NH4_conc)/mean(NH4_conc), n = n()) %>.%
  rmarkdown::paged_table(.)
```


